#!/bin/bash

# ./local_exp -targetDir "/media/rosu/Data/phd/ws/LocalExpStereo/data/MiddV2/teddy" -outputDir "/media/rosu/Data/phd/ws/LocalExpStereo/results" -mode MiddV2 -smooth_weight 1 -doDual 1 -threadNum 4 -iterations 5 -pmIterations 2 -filterRadius 20 -smooth_weight 1.0 -mc_threshold 0.5 -ndisp 59
# ./local_exp -targetDir "/media/rosu/Data/data/middelbury/Sword1-perfect/images_selected" -outputDir "/media/rosu/Data/phd/ws/LocalExpStereo/results" -mode MiddV2 -smooth_weight 1 -doDual 1 -threadNum 12 -iterations 5 -pmIterations 2 -filterRadius 20 -smooth_weight 1.0 -mc_threshold 0.5 -ndisp 300
# ./local_exp -targetDir "/media/rosu/Data/data/middelbury/Flowers-perfect/images_selected" -outputDir "/media/rosu/Data/phd/ws/LocalExpStereo/results" -mode MiddV2 -smooth_weight 1 -doDual 1 -threadNum 12 -iterations 5 -pmIterations 2 -filterRadius 20 -smooth_weight 1.0 -mc_threshold 0.5 -ndisp 1100
# ./local_exp -targetDir "/media/rosu/Data/data/middelbury/Jadeplant-perfect/images_selected" -outputDir "/media/rosu/Data/phd/ws/LocalExpStereo/results" -mode MiddV2 -smooth_weight 1 -doDual 0 -threadNum 12 -iterations 5 -pmIterations 2 -filterRadius 20 -smooth_weight 1.0 -mc_threshold 0.5 -ndisp 600

#phenorob
# ./local_exp -targetDir "/media/rosu/Data/phd/ws/LocalExpStereo/data/phenorob" -outputDir "/media/rosu/Data/phd/ws/LocalExpStereo/results" -mode MiddV2 -smooth_weight 1 -doDual 1 -threadNum 12 -iterations 5 -pmIterations 2 -filterRadius 20 -smooth_weight 1.0 -mc_threshold 0.5 -ndisp 1300
./local_exp -targetDir "/media/rosu/Data/phd/ws/LocalExpStereo/data/phenorob_sub4" -outputDir "/media/rosu/Data/phd/ws/LocalExpStereo/results" -mode MiddV2 -smooth_weight 1 -doDual 1 -threadNum 12 -iterations 5 -pmIterations 2 -filterRadius 10 -smooth_weight 1.0 -mc_threshold 0.5 -ndisp 300